version: '3.2'

services:

  history: 
    environment:
      - NODE_ENV=production

    build: history/

    depends_on:
      - 'database'

    ports:
      - '3011:3011'
    
  ratings: 
    environment:
      - NODE_ENV=production

    build: ratings/

    depends_on:
      - 'database'

    ports:
      - '3001:3001'

  proxy: 
    environment:
      - NODE_ENV=production

    # Where to find the Dockerfile
    build: proxy/

    # Control the startup order of the containers once Compose builds them
    depends_on:
      - 'database'
      - 'ratings'
      - 'history'

    # Map the port on the host to the exposed port on the container
    ports:
      - '80:80'
  
  # Define the database service
  database:

    # Spin up a container from the 'mongo:latest' image cached on the machine, or pull from Dockerhub
    image: mongo:latest

    # command: mongod --port 27017
    # expose: '27017'