version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.15.1

    steps:
      - checkout
      - run: cd ratings && npm install && npm run test && cd .. && cd history && npm install && npm run test